{ config, lib, pkgs, modulesPath, ... }:
let 
	username = "dan";
	fullName = "Dan Saul";
in
{
	environment.etc = {
		"usericons.d/${username}".source = "${./icon.png}";
	};
	
	age.secrets."userHashedPasswordFile-${username}".file = ../../secrets/userHashedPasswordFile-${username}.age;
	
	users.users."${username}" = {
		uid=1000;
		isNormalUser = true;
		description = fullName;
		hashedPasswordFile = config.age.secrets."userHashedPasswordFile-${username}".path;
		createHome = true;
		extraGroups = [
			"networkmanager"
			"wheel"
			"docker"
			"libvirtd"
			"media"
			"users"
		];
		packages = with pkgs; [

		];
		openssh.authorizedKeys.keys = [
			"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO4DXCWnspO5WUrirR33EAGTIl692+COgeds0Tvtw6Yd"
			"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDPsbysDzZnFIjgsehqZKgeVkLwT72uWdpPy0PKH6lgN57z+WP+xeEuho/V7Ok5NB+3f+ebwFpXOR6ZGrz/yAv9zCkCeRFe1pSJ8fDq1DEQfCCJkJ6/NqowWpIDRcKSLY76PTCvnv9FH5xzNVzvh/PG2iVExgiZegaSnLmxKk8q1p+Sz6HLYtykdtPta2bnOb0vr8XNgLme2+M0NlGWh53d8jN2ZPvqvCq3lt/JFADCCburEVjsVsNmj5AoK9L3kgL2P4/H/fBWtZcfiYQ8T95Rl3t4ilW2+SlChRhmnlCQproutV27uWTF4xBci7HZk667ORAOYVONU4rR/liVlYqTO5ykOU86A4+sJIg6E+H/yd2ka5DKnyTBACqcjH2KxLVeYqa7JQcjB03e+WOpYzvUe3hAJsRjpKoxixenZiZFHvs98bMfXxdfkZP/7RSXau4n2zavrL/GyfiVTBksEbuTHNKsAhIXSXAJtZ70l3XMbtANWDaa4j6oGBKPjP3CkKu8+SVtqL2fzUxqTpOP73Ita3urzrjLcMh6JCg5v25/5TzcI3n3v6yNnHn6aHpeDhJQHIo/abRTFWcp+WscNDax8WrD5fX2SLugq9OI1Oq7r4MexPXQu9D9y2rW2ZvdiioRABGcxyAd/87oFJzLGrxh1QtIF60fcHXGosLaYQMApw== generated by Keepass2Android"
		];
	};
	
	home-manager.users.dan = { pkgs, ... }: {
		home.packages = [ ];
		programs.bash.enable = true;
		
		programs.git = {
			enable = true;
			userName = "Dan Saul";
			userEmail = "dan@dsaul.ca";
		};

		# The state version is required and should stay at the version you
		# originally installed.
		home.stateVersion = "24.11";
	};
	
}
